name: CI test

on:
  push:
    branches:
      - master
      - main
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests
        working-directory: ./Quizzes

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Run tests
        run: mvn test
        working-directory: ./Quizzes
